#数据库配置信息
spring:
    datasource:
        name: qbzzSource
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:postgresql://127.0.0.1:5433/zldetc
        username: postgres
        password: 123456
        driver-class-name: org.postgresql.Driver
        minIdle: 1
        maxActive: 2
        initialSize: 1
        timeBetweenEvictionRunsMillis: 3000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false

    freemarker:
            template-loader-path: classpath:/templates/
            cache: false
            charset: UTF-8
            check-template-location: true
            content-type: text/html
            expose-request-attributes: true
            expose-session-attributes: true
            request-context-attribute: request
            suffix: .ftl

#服务器配置信息
server:
    port: 9091
#日志文件配置信息
logging:
    config: classpath:logback.xml
    level: debug

#微信支付信息
wxpay:
    unifiedorderurl: https://api.mch.weixin.qq.com/pay/unifiedorder
    timeout: 60000
    notifyurl: http://localhost:9091/pay/callback
    appid: wx426b3015555a46be
    key: 8934e7d15453e97507ef794cf7b0519d
    mchid: 1900009851
    appsecret: 7813490da6f1265e4901ffb80afaa36f
